name: Release

on:
  release:
    types: [created]

jobs:
  release:
    permissions: write-all
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
    steps:
      - uses: actions/checkout@v4
      - name: Generate file with environment variable
        run: |
          sed -i 's/dev/${{ github.event.release.tag_name }}/' src/env.rs

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
